### ISSUE TITLE
Overload of setDataProvider is redundant

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-combo-box-flow#149]
The method `setDataProvider(dataProvider, filterConverter)` is redundant, as it is the same as `setDataProvider(dataProvider.withConvertedFilter(...))`. This has caused confusion in my team, e.g.

- *why there is such a method?*
- *which signature is better?*
- *are the two invocations equivalent?*

It would be clearer in my opinion to remove the method and document the single-argument `setDataProvider` with pointers to `DataProvider::withConvertedFilter`.

**Comment by pekam** [comment]
The method signature is from the mixin interface `HasFilterableDataProvider`. Using this overload or `dataProvider.withConvertedFilter()` should be equivalent.

I see it as a nice convenience method: If my data provider's filter type is something else than String, I'll soon notice that I can't just use it in `setDataProvider()`. Then I will find out from the API that there's this another overload which accepts my data provider, but I need to also provide a converter to handle the String-filter from ComboBox.
(Consider someone who doesn't know about `withConvertedFilter()` method in advance)

So in my opinion it's good to have this method. Like you said, this info of how to convert the String-filter could be also stated in the javadocs of `setDataProvider(DataProvider<T, String> dataProvider)`, but I'd see it easier to find a method signature that accepts my data provider.

I checked the javadocs and they are just inherited from mixin interfaces and not really useful. Since this has caused confusion in your team, something should be done. Would you and the team be satisfied if the javadocs would be improved like this:

`setDataProvider(DataProvider<T, String> dataProvider)`:
- answer why it accepts only String as the filter type
- suggest converting the filter String by using either `dataProvider.withConvertedFilter` or the other overload

`setDataProvider(DataProvider<T, C> SerializableFunction<String, C> filterConverter)`:
- explain why the converter is needed
- mention that the same can be done with `dataProvider.withConvertedFilter`

**Comment by heruan** [comment]
Yeah, that would be much clearer! Thank you @pekam 🙂
