### ISSUE TITLE
Reintroduce the CaptionFilter concept in ComboBox

### ISSUE THREAD

**Issue by ahie** [vaadin/vaadin-combo-box-flow#17]
@ahie commented on [Mon Nov 20 2017](https://github.com/vaadin/flow/issues/2976)

Currently the `ComboBox` component is missing the `CaptionFilter` interface and related methods from FW8. `CaptionFilter` together with the overloads for `setDataProvider` and `setItems` provides a simple way for configuring a custom filter converter on the used data provider.

Once this feature is implemented the corresponding lines in the tutorial flow tutorial `flow-documentation/data-provider/tutorial-flow-data-provider.asciidoc` and source file `DataProviders.java` should be uncommented.

**Comment by pekam** [comment]
I propose to have an `ItemFilter extends SerializableBiPredicate<T, String>` instead of `LabelFilter extends SerializableBiPredicate<String, String>`. The default behavior would be the same as in V8, so it would run the `ItemLabelGenerator` and use lower-case-contains for filtering.

Reason for using the item-type in the predicate:
In case you use renderers, like in the [component renderer example](https://vaadin.com/components/vaadin-combo-box/java-examples/using-components), the label shows only the name of the song, but also the artist is rendered in the dropdown. So you might want to use both the song name and the artist name in the filtering.
