### ISSUE TITLE
ComboBoxes that fetches data with dataproviders show incorrect rows when refreshing

### ISSUE THREAD

**Issue by brp-benjamin** [vaadin/vaadin-combo-box-flow#177]
After refreshing a dataprovider such that you get fewer rows than currently shown the rest of the rows will be filled with empty dummy rows.

I have modified the demo to show this bug in:

https://github.com/brp-benjamin/vaadin-combo-box-flow/tree/combobox-overlay-bugs

Attached is a screenshot of the bug

![card-overlay-error-screenshot](https://user-images.githubusercontent.com/42134286/50217182-4f287d80-0388-11e9-91e3-ffb76fde38c6.png)

**Comment by denis-anisimov** [comment]
Please provide a code example which we may use to reproduce the issue.
You may use https://github.com/vaadin/skeleton-starter-flow project for that.

**Comment by heruan** [comment]
I'm also experiencing this, reproducible with:

https://github.com/heruan/vaadin-spring-demo/blob/04d8ee803eefbf0fc0c759b75a8ef6d14cab7314/src/main/java/to/lova/vaadin/spring/ComboBoxRefresh.java#L15-L29

**Comment by denis-anisimov** [comment]
Thanks for the exact code !

Here is the complete Java 8 code snippet :
```
@Route("refresh")
public class ComboBoxRefresh extends Div {
    public ComboBoxRefresh() {
        add(new H1("ComboBox refresh"));
        List<String> list = new ArrayList<String>();
        list.add("Foo");
        list.add("Bar");
        DataProvider<String, String> dp = DataProvider
                .<String, String> fromFilteringCallbacks(q -> list.stream()
                        .skip(q.getOffset()).limit(q.getLimit()),
                        q -> list.size());
        ComboBox<String> cb = new ComboBox<String>();
        cb.setDataProvider(dp);
        this.add(cb, new NativeButton("Refresh", event -> {
            list.remove("Foo");
            dp.refreshAll();
        }));
    }
}
```

Steps to reproduce:
- Open combo box dropdown.
- See there are two items "Foo" and "Bar".
- Close it
- Click "refresh" button.
- Open combo box dropdown.
- See there are two items  "Bar" and an empty one.

Expected: after the removal there should be only one item shown "Bar".

It might be this is a client side issue.

**Comment by heruan** [comment]
Any update on this? Still an issue in V12 release and V13 pre-release.

**Comment by heruan** [comment]
Not sure if related, but when using a component renderer after a `refreshAll` when the number of returned items is less than before that instead of the empty lines I still see the old renderer content.

**Comment by heruan** [comment]
Still no feedback on this? This impacts the user experience, as users are confused by empty lines and think there are options missing from the list.

**Comment by brp-benjamin** [comment]
What is the plan regarding this issue?

It's been more than a month and it gives very glaring errors. I realize the minimal screenshot makes this look like a minor cosmetic issue, but when you are using a filtered combobox to select from a larger dataset this could result in thousands of empty placeholder lines.

**Comment by pekam** [comment]
Sorry for having to wait for this, we'll start investigating the issue now.

**Comment by pekam** [comment]
It's a client-side bug which can be reproduced with the web component without Flow integration:
1. Set a `comboBox.dataProvider` function which returns multiple items
2. Open and close the combo box
3. Call `comboBox.clearCache()`
4. Change the conditions so that the data provider returns only one item, eg. `callback(['foo'], 1);`
5. Open the combo box and notice that the combo box contains the item 'foo' plus a lot of placeholders, even though `comboBox.size === 1`

**Comment by Fr33z3m4n** [comment]
same #159

**Comment by pekam** [comment]
Thanks for pointing that out @Fr33z3m4n!

The fix is merged in the web component repository: https://github.com/vaadin/vaadin-combo-box/pull/771

A test for the Flow component is waiting for a new web component release: https://github.com/vaadin/vaadin-combo-box-flow/pull/205

We're not going to release the web component immediately, as we will likely make another bug fix in it first.
