### ISSUE TITLE
Filtering seems to not work in all cases

### ISSUE THREAD

**Issue by ttsanton** [vaadin/vaadin-combo-box-flow#182]
_Running on 13.0.0.alpha1_

I have a basic ComboBox:
```
ComboBox<String> testBox = new ComboBox<>("Browsers");
testBox.setItems("Google Chrome", "Mozilla Firefox", 
           "Opera", "Apple Safari", "Microsoft Edge");	
```
![filterbad](https://user-images.githubusercontent.com/7467196/50654619-6d32d800-0f5b-11e9-9509-d18a0c2cd3c5.gif)

I can select values manually just fine, but if I try to filter and type into the Combo Box, it just gives an empty dropdown. I also tried on 12.0.3, and it happens there, too.

What's interesting, though, is when I set Items of the Combo Box to a long list of values and filter these, it works fine:
```
ComboBox<String> country_resident = new ComboBox<>("Country of Residence");
country_resident.setItems(countries); //countries is a List<String> of 300+ values
```
![filtergood](https://user-images.githubusercontent.com/7467196/50654358-943cda00-0f5a-11e9-9bb0-c0d8b9f19db5.gif)

**Comment by mpilone** [comment]
I'm seeing the same issue using v12. It seems to be related to when the ComboBox uses client side filtering. If server side filtering is used, due to a large data set or forced with setItems(filter, items) things work fine.

For example, with a small data set (5 items), this call fails to support filtering:
```
comboBox.setItems(itemArray);
```

But this call does properly support filtering:
```
typeCmb.setItems((item, filterText) ->
        Strings.isNullOrEmpty(filterText) || item.getCaption().toLowerCase().contains(filterText.toLowerCase()), itemArray);
```

**Comment by bogdanudrescu** [comment]
Fixed by https://github.com/vaadin/vaadin-combo-box-flow/pull/192
