### ISSUE TITLE
vaadin-combo-box value, _inputElementValue, and itemValuePath seemingly incorrect sometimes

### ISSUE THREAD

**Issue by Silver-Wulf** [vaadin/vaadin-combo-box-flow#187]
When working on issue #180 I looked into why the ComboBox would display numbers when the value was set to null. Looking further into it I noticed that the "itemValuePath" property, although initialized as "value" would change to "key" after the page loaded, even before the code was executed for the ComboBox's Selected Value Changed listener.

![image](https://user-images.githubusercontent.com/16447048/51081000-f1473700-16a2-11e9-85a9-dd67037578d4.png)

This was normally unnoticeable except for when the value was set to null using the ComboBox setValue() in Java.

When I debugged the values of the "value" and the variable that was actually shown, "_inputElementValue", the values would be different even if setValue(null) had never been invoked. The "value" property was the key and the "_inputElementValue" was the value because the "value" property is assigned based on the "itemValuePath" (which is strangely "key" only after the page loads)

![image](https://user-images.githubusercontent.com/16447048/51081029-63b81700-16a3-11e9-86f8-207168b63295.png)

These two variables are synchronized sometimes and in #180 the "value" property's value was shown which is why numbers corresponding to the element's keys appeared instead of the elements themselves (as value was not previously set to null properly in setValue() before my pull request #186 ).

Is this intentional?

**Comment by pekam** [comment]
- Setting `itemValuePath = 'key'` is part of the Flow component implementation which allows us to map the json objects in the combo box to the corresponding Java beans by their internal ids (keys).
- Because of this, it is also intentional that the `value` property of the combo box corresponds to the `key` property of the selected item.
- The `_inputElementValue` should reflect to what is shown in the text field. The property-name of the selected item which is shown in the text field is defined by `itemLabelPath = 'label'`.

I'm not sure what caused the bug that made the `key` property visible in the text field, but seems that you fixed that one.

Is this explanation enough to close this issue?

**Comment by pekam** [comment]
I'm closing this issue because
- it's considering implementation details instead of component users
- nothing seems to be actually broken
- the author hasn't replied to my comment after several months
