### ISSUE TITLE
Custom value set fired in multiple scenarios when setAllowCustomValue is false

### ISSUE THREAD

**Issue by eriklumme** [vaadin/vaadin-combo-box-flow#212]
## Example 1: Lazy loading combo-box, allow custom value = false

    ComboBox<String> combo = new ComboBox<>();
    combo.setItems(String::contains, Arrays.asList("One", "Two", "Three", "Four", "Five", "Six"));
    combo.setAllowCustomValue(false);

    combo.addCustomValueSetListener(e -> Notification.show("Set custom value " + e.getDetail(),
            3000, Notification.Position.TOP_CENTER));
    combo.addValueChangeListener(e -> Notification.show("Set value " + e.getValue(),
            3000, Notification.Position.TOP_CENTER));

#### Steps to reproduce

1. Type e.g. `asd` or `Fou` into the combo-box
2. Wait for the combo-box to load or press enter

#### Expected outcome

No events are fired

#### Actual outcome

Custom value set is fired twice with the value typed, e.g. `asd`

#### Steps to reproduce

1. Type `F` into the combo-box
2. Select either `Four` or `Five`, using the keyboard or the mouse

#### Expected outcome

Value changed event fired with the selected value

#### Actual outcome

Custom value event fired twice for the selected value. If the combo-box already had a value, value changed event is fired with `null`.

## Example 2: Normal combo-box, allow custom value = false

    ComboBox<String> combo = new ComboBox<>();
    combo.setItems(Arrays.asList("One", "Two", "Three", "Four", "Five", "Six"));

    combo.setAllowCustomValue(false);

    combo.addCustomValueSetListener(e -> Notification.show("Set custom value " + e.getDetail(),
            3000, Notification.Position.TOP_CENTER));
    combo.addValueChangeListener(e -> Notification.show("Set value " + e.getValue(),
            3000, Notification.Position.TOP_CENTER));

    add(combo);

#### Steps to reproduce

1. Type anyhing

#### Expected outcome

No events are fired

#### Actual outcome

Custom value set event fired twice per letter

#### Steps to reproduce

1. Type `F`
2. Click `Four`
3. Clear the combo box and type `F` again
4. Select `Five` using the keyboard

#### Expected outcome

Selecting `Four`, a value change event is fired. 
Selecting `Five`, another value changed event is fired.

#### Actual outcome

Selecting `Four`, a value change event is fired.
Selecting `Five`, a value change to `null` and  a custom value set event is fired.

## Versions

`combo-box-flow` version `2.0.3` or `2.1.0`, otherwise platform `12.0.5`.

**Comment by pekam** [comment]
Some insight to a couple of the described problems:

**Firing events after calling `setAllowCustomValue(false)`:**

The JavaDocs of `addCustomValueSetListener` states:
> As a side effect makes the ComboBox allow custom values. If you don't want to allow a user to add new values to the list once the listener is added please disable it explicitly via the setAllowCustomValue(boolean) method.

So it works as documented, although I agree that this kind of behavior seems really unexpected.

**Duplicate custom value set events:**

This was a bug in the web component, also described in #167. The fix was released in `vaadin-combo-box v4.2.9`

**Comment by pekam** [comment]
> Custom value set when selecting a filtered value

I've created a bug ticket for the web component: https://github.com/vaadin/vaadin-combo-box/issues/804 (fix in progress)

> If the combo-box already had a value, value changed event is fired with null

I think this should be fixed via #255, included in 3.0.0.rc1.

I think that should cover pretty much the issues described here, so I'm closing the issue. You can re-open it if I'm missing something, or better yet, create a new ticket since this one describes quite many separate issues.

Overall, the custom-value feature is finally properly tested and it should be working and more usable in V14.
