### ISSUE TITLE
Updating from vaadin 12.0.0 the combo box will set the value to null when setting the binder item to something from page 2 or later

### ISSUE THREAD

**Issue by brp-benjamin** [vaadin/vaadin-combo-box-flow#216]
Reproduced with vaadin skeleton flow for versions 12.0.6 and 13.0-SNAPSHOT. The bug does not exist in vaadin 12.0.0

 * Given: a combo box which is set with a binder and have multiple pages of items (51+)
 * When: you select something from page 2 or later with the help of a filter and set the binder to the same item
 * Then: the combo-box is unexpectedly set to null

It is as if the combo box remembers which page it found the item on and is confused when it is no longer there. The bug does not appear if you select something from the first page, or if you select something from the second page by scrolling to it.

See screenshot:
![bild](https://user-images.githubusercontent.com/42134286/53006251-2595dc00-3435-11e9-8f7c-4e1f5e3d7665.png)

See reproducible example:
https://github.com/brp-benjamin/skeleton-starter-flow/tree/pagination-and-filter-issues for implementation.

**Comment by pekam** [comment]
Thanks for the issue and again for a clear code example!

Started investigating the bug. Some findings so far:
- To narrow down the problem, the bug can be reproduced without binder by re-setting the current value to combo box: `comboBox.setValue(comboBox.getValue());`.
- It was caused by something between versions 2.0.2 and 2.0.3 https://github.com/vaadin/vaadin-combo-box-flow/compare/2.0.2...2.0.3
