### ISSUE TITLE
Avoid calling DataProvider::size before data is requested

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-combo-box-flow#242]
Follow-up of #222.

The `DataCommunicator` constructor calls `requestFlush`, which in turn calls `DataProvider::size`. This size query might be expensive to execute. Currently the `DataCommunicator` is initialized already in `ComboBox::setDataProvider`.

As an optimization, we could postpone the initialization of the `DataCommunicator` to the moment when `ComboBox` is opened and data is requested for the first time. This would avoid unnecessarily calling `DataProvider::size` for those `ComboBoxes` which the user never opens.

**Comment by mshabarov** [comment]
The following code changes in `ComboBox` have been done in order to optimise the size queries for lazy data providers:
- `DataCommunicator` initialisation isn't now happen immediately when setting the data provider, but later-on, when the user opens the dropdown list. The initialisation code is placed into a callback which is invoked upon the `setRequestedRange` call.
- For a in-memory data providers the initialisation takes place immediately, because there is no database requests delay in this case.
- As previously, if no data provider is set to the component, the empty items list is used.

These changes apparently break the `connector` behaviour, because now the `AutoFocusFilterIT` is failing permanently, with a reason that there are no items rendered on client-side. The items data and the actual items count are sent to client properly, and visually there are two items, but the slots are completely empty.

![Screenshot 2020-08-03 at 15 36 58](https://user-images.githubusercontent.com/61410877/89182968-35f53480-d59f-11ea-80fc-62abe291b1b3.png)

As we figured out with @tomivirkki during a short investigation session is that the client actually sends two requests with an empty filter and then with exact that user inputs ("2" in case of IT test).

Further investigations on `connector` side should be done to find the root cause of why those two item's labels are failed to be rendered.

**Comment by caalador** [comment]
It would seem like the issue is that the dataprovider is initialized when the first requestData comes from the client it does a reset which makes the filter debouncer get overridden with a requestData debouncer and the inintial debouncer is never called.
Having the latter debounce comboBoxConnector:l149 clear the page callbacks then all tests pass with the new delayed initialization.

another problem as seen in the screenshot in the previous comment is that the reset from the server clears the `2` from the input field that was typed there.
