### ISSUE TITLE
Combo-box should have api for specifying the null-representation

### ISSUE THREAD

**Issue by mhosio** [vaadin/vaadin-combo-box-flow#46]
Currently there is no api for combobox to specify null-representation. Still quite a few times the bound bean may have null as a field value that we almost never want to show to the end user. Would be nice to just specify combobox.setNullRepresentation("") instead of applying workarounds with ItemLabelGenerator.

**Comment by chrisspelberg** [comment]
It would be nice if it would behave like the placeholder text in the TextField component.

**Comment by pleku** [comment]
### Acceptance Criteria
There is API for _specifying the null representation_, which corresponds to the _null_ value being set to the CB.
There is a demo that showcases this feature

**Comment by pekam** [comment]
`setNullRepresentation` API was added in 1.1 release, but I'm concerned that it doesn't really serve it's purpose. In the demo there is a `null` value added to the set of options, and the null representation is shown as its label. The original issue might have been misunderstood.

ComboBox should always show an empty string after setting a `null` value to it. If you want to see something else like "Please enter a value" in this case, you should use `setPlaceholder`. Then the text is shown in a lighter shade of grey so that it is not mistaken for a real value.

@mhosio does this sound fine for you?

I'm planning to remove the current `setNullRepresentation` API because it expects to have `null` values in the data set, which is not allowed when using data providers. But I'd like you to verify first what is the original intention of this ticket.

**Comment by ZheSun88** [comment]
I remember that we had two different implementations for this issue and there is a confusion on the `null` value representations, Pekka H. pointed the current implementation so as you can notice from the commit, it contains some revert changes.

**Comment by pleku** [comment]
>ComboBox should always show an empty string after setting a null value to it. If you want to see something else like "Please enter a value" in this case, you should use setPlaceholder. Then the text is shown in a lighter shade of grey so that it is not mistaken for a real value.

The `null` and "nothing selected" are two different things:
1. Having a ComboBox where the user has not selected anything -> place holder is shown "Please select a meal", no value yet
2. Having a ComboBox where `null` is a valid value (eg. "Select meal:" -> _no meal_ or similar) and the user is still forced to make a selection (required field), eg. they need to explicitly select the `null` value. It might have a visual representation of "No Meal"

For the web component - the `null selection item` is just another item with caption. It is like applying automatically conversion (on server side) from `null` to the specified string. 

If the `DataProvider` doesn't allow `null` items, that just means that for those cases the `nullRepresentation` has no effect since there is no `null` item in the data set.

(In the FW8 version, the API is named `emptySelection`, there is also a boolean flag which states that the empty selection can be disabled/enabled. If you look at the component in sampler, you can test it, but I warn you that it appears to be quite broken ... )

**Comment by Legioth** [comment]
The _no meal_ case based on a `null` item makes no sense since the application logic cannot see the difference between nothing selected and _no meal_ selected because both cases would have `getValue() == null`, and it would thus not be accepted by a server-side required validator. For this use case to actually work, you'd have to have an explicit non-null value in the data provider, and then the null representation feature wouldn't be used.

For the null representation feature to make sense, we would need explicit support for a `null` value in the data provider (or items array, which is just a shorthand for a `ListDataProvider). Until we have that functionality as well, null representation makes no sense at all (and should thus be removed). But adding that feature makes no sense either since it's then again indistinguishable from an empty value.
